# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
   os: ubuntu-24.04
   tools:
      python: "3.13"
   apt_packages:
      - build-essential
      - flex
      - bison
      - curl
      - pkg-config
      - llvm
      - clang
      - libreadline-dev
      - libssl-dev
      - libicu-dev
      - liblz4-dev
      - libossp-uuid-dev
      - python3-dev
      - git
      - unzip
      - zstd
      - lsof
   jobs:
      pre_create_environment:
         - tools/rtd-setup.sh
      pre_build:
         - sphinx-apidoc --ext-autodoc --module-first -o docs/source/generated postbound

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# Optionally, but recommended,
# declare the Python requirements required to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
      - requirements: requirements.txt
