
-- DB configuration generated by postgres-config-generator.py
-- Generated on: 2025-07-01 14:36:40
-- Data directory: '/pg_lab/pg-build/pg-17/data'
-- Generator based on rules from PGTune by le0pard (https://pgtune.leopard.in.ua/)

ALTER SYSTEM SET max_connections = '40';
ALTER SYSTEM SET huge_pages = 'off';
ALTER SYSTEM SET shared_buffers = '1959MB';
ALTER SYSTEM SET effective_cache_size = '5878MB';
ALTER SYSTEM SET maintenance_work_mem = '1GB';
ALTER SYSTEM SET min_wal_size = '4GB';
ALTER SYSTEM SET max_wal_size = '16GB';
ALTER SYSTEM SET checkpoint_completion_target = '0.9';
ALTER SYSTEM SET wal_buffers = '16MB';
ALTER SYSTEM SET default_statistics_target = '500';
ALTER SYSTEM SET random_page_cost = '1.1';
ALTER SYSTEM SET effective_io_concurrency = '200';
ALTER SYSTEM SET max_parallel_workers_per_gather = '5';
ALTER SYSTEM SET max_worker_processes = '10';
ALTER SYSTEM SET max_parallel_workers = '10';
ALTER SYSTEM SET max_parallel_maintenance_workers = '4';
ALTER SYSTEM SET work_mem = '5MB';
